# Utilizar la imagen de Python 3.8 como base
FROM python:3.8

# Establecer el directorio de trabajo de la imagen de Docker en el directorio de la aplicación Flask
WORKDIR /app

COPY dictionary/dic_cars_modelo.json /app/dictionary/dic_cars_modelo.json
COPY requirements.txt /app/requirements.txt
COPY models/cars_model.pkl /app/models/cars_model.pkl
COPY models/message_model.pkl /app/models/message_model.pkl
COPY queries/query_cars.py /app/queries/query_cars.py
COPY recollect_cars/recollect_cars.py /app/recollect_cars/recollect_cars.py
COPY tokenizer/tokenizer.py /app/tokenizer/tokenizer.py
COPY app.py /app/app.py


# Instalar las dependencias del proyecto Flask
RUN pip install -r requirements.txt

EXPOSE 5000

# Especificar el comando que se utilizará para ejecutar la aplicación Flask dentro del contenedor de Docker
CMD [ "python", "-m" , "flask", "run", "--host=0.0.0.0", "--port", "5000"]