// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzHlqZ2ZilJ1oIm53Z0XOnRD0jARLbUeQ',
    appId: '1:728889994564:web:7cdd60017dcf033a4afb11',
    messagingSenderId: '728889994564',
    projectId: 'padook-5be51',
    authDomain: 'padook-5be51.firebaseapp.com',
    storageBucket: 'padook-5be51.appspot.com',
    measurementId: 'G-GNQ45GVN9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgqHcBO7LajEAEIyPggLJ-xcEhP88LvTU',
    appId: '1:728889994564:android:311c761623793ab04afb11',
    messagingSenderId: '728889994564',
    projectId: 'padook-5be51',
    storageBucket: 'padook-5be51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKOkznzN2QICsbHJfaJkLo-QVN9enD7Vs',
    appId: '1:728889994564:ios:c6b8059b5dd240c04afb11',
    messagingSenderId: '728889994564',
    projectId: 'padook-5be51',
    storageBucket: 'padook-5be51.appspot.com',
    iosClientId: '728889994564-3302vd2rs5ac6k28al7vm4bng6pc21b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.padook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKOkznzN2QICsbHJfaJkLo-QVN9enD7Vs',
    appId: '1:728889994564:ios:c6b8059b5dd240c04afb11',
    messagingSenderId: '728889994564',
    projectId: 'padook-5be51',
    storageBucket: 'padook-5be51.appspot.com',
    iosClientId: '728889994564-3302vd2rs5ac6k28al7vm4bng6pc21b0.apps.googleusercontent.com',
    iosBundleId: 'com.example.padook',
  );
}
